name: ⚡ Feature - Tarea Específica
description: Crear una tarea específica de desarrollo
title: "Título del issue..."
labels: ["priority-medium"]
assignees:
  - tu-usuario-github
body:
  - type: input
    id: task-title
    attributes:
      label: 📝 Título de la Tarea
      description: Descripción concisa de lo que hay que implementar
      placeholder: "ej: Crear página de contacto con formulario"
    validations:
      required: true

  - type: dropdown
    id: epic-parent
    attributes:
      label: 🎯 Épica Padre
      description: ¿A qué épica pertenece esta tarea?
      options:
        - 🏗️ Estructura Base del Sitio
        - 🎨 Sistema de Temas Claro/Oscuro
        - 🖼️ Galería Interactiva
        - 📱 Diseño Responsivo
        - 📋 Formularios con Validación
        - 🎪 Animaciones y Transiciones
        - ♿ Accesibilidad Web
        - ⚡ Optimización y Performance
    validations:
      required: true

  - type: dropdown
    id: technology
    attributes:
      label: 💻 Tecnología Principal
      description: ¿Qué tecnología usarás principalmente?
      options:
        - HTML - Estructura y contenido
        - CSS - Estilos y diseño
        - JavaScript - Interactividad
        - Assets - Imágenes, videos, recursos
        - Documentation - Documentación
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: 📖 Descripción Detallada
      description: Explica específicamente qué hay que implementar
      placeholder: "Describe los pasos específicos, elementos a crear, funcionalidades..."
    validations:
      required: true

  - type: checkboxes
    id: tasks
    attributes:
      label: ✅ Lista de Tareas
      description: Desglosa la tarea en pasos específicos
      options:
        - label: Crear estructura HTML básica
        - label: Implementar estilos CSS
        - label: Agregar JavaScript si es necesario
        - label: Testing en múltiples navegadores
        - label: Validar accesibilidad básica
        - label: Documentar código implementado

  - type: input
    id: estimation
    attributes:
      label: ⏱️ Estimación (horas)
      description: Tiempo estimado para completar
      placeholder: "ej: 3"
    validations:
      required: true

  - type: dropdown
    id: difficulty
    attributes:
      label: 🎯 Dificultad
      description: Nivel de complejidad técnica
      options:
        - 🟢 Fácil - Conocimientos básicos
        - 🟡 Medio - Requiere investigación
        - 🔴 Difícil - Conocimientos avanzados
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: 🚨 Prioridad
      description: Importancia para el proyecto
      options:
        - 🔴 Critical - Bloqueante para entrega
        - 🟠 High - Importante para funcionalidad
        - 🟡 Medium - Mejora la experiencia
        - 🟢 Low - Nice to have

  - type: dropdown
    id: evaluation-criteria
    attributes:
      label: 📊 Criterio de Evaluación
      description: ¿A qué criterio del curso contribuye?
      options:
        - 📝 APF1 - Estructura HTML (25%)
        - 📝 APF1 - Formularios (25%)
        - 📝 APF1 - Tablas (20%)
        - 📝 APF1 - Multimedia (15%)
        - 📝 APF1 - SEO/Meta tags (15%)
        - 🎨 APF2 - Sistema Temas (30%)
        - 🎨 APF2 - Responsive (25%)
        - 🎨 APF2 - Animaciones (20%)
        - 🎨 APF2 - Personalización (15%)
        - 🎨 APF2 - Mobile First (10%)
        - ⚡ APF3 - Galería Filters (25%)
        - ⚡ APF3 - Lightbox (20%)
        - ⚡ APF3 - Form Validation (20%)
        - ⚡ APF3 - Responsive Menu (20%)
        - ⚡ APF3 - LocalStorage (15%)
        - 🚀 PROY - Integración (25%)
        - 🚀 PROY - Funcionalidad (25%)
        - 🚀 PROY - UX/UI (20%)
        - 🚀 PROY - Código Limpio (15%)
        - 🚀 PROY - Accesibilidad (10%)
        - 🚀 PROY - Performance (5%)

  - type: textarea
    id: acceptance-criteria
    attributes:
      label: ✅ Criterios de Aceptación
      description: ¿Cómo sabrás que la tarea está completa?
      placeholder: |
        - [ ] Criterio específico 1
        - [ ] Criterio específico 2
        - [ ] Criterio específico 3
      value: |
        - [ ] Funcionalidad implementada según especificación
        - [ ] Testing realizado sin errores
        - [ ] Código validado y documentado

  - type: textarea
    id: dependencies
    attributes:
      label: 🔗 Dependencias
      description: Tareas que deben completarse antes/después
      placeholder: |
        **Depende de:** Issue #XX - [descripción]
        **Bloquea a:** Issue #XX - [descripción]